# Generated by Django 4.2.11 on 2025-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('playlist', 'Playlist'), ('video', 'Video'), ('short', 'Short')], default='video', max_length=20),
        ),
    ]
