# Generated by Django 4.2.11 on 2025-05-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
