# Generated by Django 4.2.11 on 2025-06-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="link",
            field=models.URLField(max_length=400),
        ),
    ]
